### ISSUE TITLE
rxmask with react controlled component

### ISSUE THREAD

**Issue by theTriss** [kmeshavkin/rxmask#1]
I have a one questions, how to use this mask with react controlled components?

**Comment by kmeshavkin** [comment]
It's usually harder to use with controlled components, because you need to set both value and selectionStart + selectionEnd of cursor yourself, but if you want to, you can use this part of tutorial: https://github.com/kmeshavkin/rxmask#use-it-to-parse-raw-string-value for value parsing + React refs to set cursor position.

Basically, you need to do initial set up:
```javascript
import rxmask from 'rxmask';
const parser = new rxmask(/* param object */);
```

Then provide parser with input value (you will probably have it stored in state if it's controlled component) and then call parseMask() function:
```javascript
parser.options.value = /* input value */;
parser.parseMask();
```

At this point you will have parsed (transformed) input value and cursor position you need in the parser object:
```javascript
const value = parser.output;
const cursorPos = parser.finalCursorPos;
```

Now you have both values required, so you need to provide them to your controlled component.

Value itself should be pretty straightforward - you just pass it to component as value.

For cursor position you need a React reference, which holds reference to real DOM element which you can modify (it should be created like this: `const ref = React.createRef()` somewhere in the constructor, read more about refs here: https://reactjs.org/docs/refs-and-the-dom.html). This ref should be provided to your component and you can use it in onChange or wherever you want to set cursor position. Here's code sample:
```javascript
<YourControlledInput
  value={value}
  inputRef={ref}
  onChange={() => {
    ref.current.selectionStart = ref.current.selectionEnd = cursorPos;
  }}
/>
```

And that's it! I'll close this issue, please let me know if you will need additional help with that code.
